services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    jalismrs_event_loop.loop_event_listener:
        class: 'Jalismrs\Symfony\Bundle\JalismrsLoopEventBundle\EventListener\LoopEventListener'

    Jalismrs\Symfony\Bundle\JalismrsLoopEventBundle\EventListener\LoopEventListener: '@jalismrs_event_loop.loop_event_listener'
