services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    jalismrs_event_loop.loop_event_subscriber:
        class: 'Jalismrs\Symfony\Bundle\JalismrsLoopEventBundle\EventSubscriber\LoopEventSubscriber'

    Jalismrs\Symfony\Bundle\JalismrsLoopEventBundle\EventSubscriber\LoopEventSubscriber: '@jalismrs_event_loop.loop_event_subscriber'
