services:
    _defaults:
        public: false
    
    event_loop.loop_event_subscriber:
        class: 'Jalismrs\EventLoopBundle\LoopEventSubscriber'

    Jalismrs\EventLoopBundle\LoopEventSubscriber: '@event_loop.loop_event_subscriber'
